version: "3.9"

services:
  java_app:
    container_name: franchiseMaker
    image: franchise-macker-app:1.0.0
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=mysql://autorack.proxy.rlwy.net:53817/railway
      - DB_USER=root
      - DB_PASSWORD=QFqwdGdVoyrplChPMOyEqoQUlqsJpEOa



